import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            colors: {
                'on-primary-fixed-variant': '#265100',
                'surface-container-lowest': '#ffffff',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'surface-container-high': '#e8e8e3',
                'tertiary-fixed-dim': '#b1d446',
                'on-secondary-fixed': '#0f2000',
                'on-tertiary': '#ffffff',
                'on-primary': '#ffffff',
                'surface-variant': '#e3e3de',
                'inverse-surface': '#2f312e',
                tertiary: '#3e5000',
                'on-error-container': '#93000a',
                'secondary-fixed-dim': '#9dd75a',
                'surface-container-low': '#f4f4ef',
                'on-tertiary-fixed-variant': '#3c4d00',
                'on-primary-container': '#b2ed83',
                background: '#fafaf5',
                'on-background': '#1a1c19',
                'inverse-primary': '#9dd770',
                'surface-dim': '#dadad5',
                'tertiary-fixed': '#ccf05f',
                'surface-container-highest': '#e3e3de',
                'inverse-on-surface': '#f1f1ec',
                'surface-tint': '#386a0e',
                primary: '#275300',
                'secondary-container': '#b7f473',
                'on-tertiary-container': '#c7eb5a',
                'primary-fixed': '#b8f389',
                'outline-variant': '#c2c9b7',
                'tertiary-container': '#536900',
                'on-surface-variant': '#42493b',
                'on-surface': '#1a1c19',
                surface: '#fafaf5',
                'primary-fixed-dim': '#9dd770',
                'on-secondary-fixed-variant': '#2d5000',
                'primary-container': '#3b6d11',
                'on-secondary': '#ffffff',
                'on-tertiary-fixed': '#161e00',
                'surface-container': '#eeeee9',
                secondary: '#3e6a00',
                error: '#ba1a1a',
                'surface-bright': '#fafaf5',
                'secondary-fixed': '#b7f473',
                'on-primary-fixed': '#0c2000',
                outline: '#727969',
                'on-secondary-container': '#427000',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            fontFamily: {
                headline: ['Hanken Grotesk'],
                display: ['Hanken Grotesk'],
                body: ['Hanken Grotesk'],
                label: ['Hanken Grotesk'],
            },
        },
    },

    plugins: [forms],
};
